### PR TITLE
Merge 1.8.14

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

Update 2.0 repositories with the relevant 1.8.14 changes.

#### Description of Proposed Changes

Merged changes from upstream and rolled over the version for the 2.0.0-rc.2 release.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects-2_merge-1.8.14

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus-2](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus-2~merge-1.8.14~CI/)

### CODE REVIEW

**Comment by donna-marijne** [comment]
Please verify (including testing) that the changes you have made in 1.8.x have been correctly merged into this branch. Refer to the commit history to check which PRs are included in this merge.

Don't merge until everyone has had a chance to review, thanks.

**Review by TaraTodd123 — APPROVED** [review]
Looks Good!

**Review by cmallon367 — APPROVED** [review]
Looks good to me

**Comment by andrewstevenson-microfocus** [comment]
Yep, all good!

**Comment by andrew-Jolly** [comment]
Looks good to me.

**Review by andrew-Jolly — APPROVED** [review]
Looks good to me.

**Comment by donna-marijne** [comment]
Thanks very much everyone.

**Pull request merged**
