### PR TITLE
Fixing dragula import Angular 9.1

### PR DESCRIPTION
**Pull request by ashley-hunter**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

https://portal.digitalsafe.net/browse/EL-3795

#### Description of Proposed Changes

Angular 9.1 has been released and running a production build produces some runtime errors based on our dragula import. Essentially we were trying to access the `default` property on the imported object and if it is undefined then fallback to a different value (to support both webpack and systemjs importing).

However, default is the internal property for a module with a default export, and webpack is now transforming this code to assume its a regular default export (I assume this is an optimization attempt):

image

This has now essentially transformed the code we have written which should in fact be:

```
const dragula = dragula_dist_dragula__WEBPACK_IMPORTED_MODULE_1__.default || dragula_dist_dragula__WEBPACK_IMPORTED_MODULE_1__;
```

So I have updated our code so that webpack won't perform any unexpected transformations

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects-2_fix-dragula

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus-2](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus-2~fix-dragula~CI/)

### CODE REVIEW

**Comment by donna-marijne** [comment]
How should this be tested? Is there something we can add to https://github.houston.softwaregrp.net/caf/ux-aspects-deploy-test perhaps?

**Comment by ashley-hunter** [comment]
Updating ng9 to 9.1 should be enough. The app won't load at all without this fix. Would you like me to bump ng9 to 9.1? Or do I create a ng9.1?

**Comment by donna-marijne** [comment]
No I think we can just bump the existing repos, thanks.

**Comment by ashley-hunter** [comment]
No problem, I will do that now

**Comment by ashley-hunter** [comment]
Deploy tests repo has now been updated: https://github.houston.softwaregrp.net/caf/ux-aspects-deploy-test/pull/1

**Review by donna-marijne — APPROVED** [review]
Thank you, I was able to reproduce the issue and confirm the fix so this is all good!

**Pull request merged**
