### PR TITLE
EL-3489 - Remove AngularJS styles

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licenced under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue
https://portal.digitalsafe.net/browse/EL-3489

#### Description of Proposed Changes
* Removed many unused style rules. Some Less files were  removed altogether.
* Removed several sections from CSS page, and renamed Page Header to Breadcrumbs.
* Moved Customize related styles into the documentation. This affected some of the screenshots for pages which included those styles. The ux-select test pages in particular were modified with an alternate layout for the customization controls.
* Made a small change to the docker script to suppress unnecessary NPM errors on exit.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects-2_EL-3489-remove-angularjs-styles

### CODE REVIEW

**Comment by ashley-hunter** [comment]
Looks great! Just noticed a few small issues:

1. Flippable Cards

All the cards now have an arrow in the top right corner:
image

2. The line height of the `pre` tag in our code snippets has changed:

[Image from Gyazo](https://gyazo.com/1a9acc87953bca6868fbe42f7b984677)

3. Dropdown Addons

In this section the dropdown no longer works, because the code uses bootstrap's js file and jquery. Perhaps we should remove the dropdown related code from this example and just show the input code?

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects-2_EL-3489-remove-angularjs-styles/#/css/text-inputs#dropdown-addons

4. Bar Chart

The last two items no longer show a dotted border

image

**Review by ashley-hunter — CHANGES_REQUESTED** [review]
Looks great! Just noticed a few small issues:

1. Flippable Cards

All the cards now have an arrow in the top right corner:
image

2. The line height of the `pre` tag in our code snippets has changed:

[Image from Gyazo](https://gyazo.com/1a9acc87953bca6868fbe42f7b984677)

3. Dropdown Addons

In this section the dropdown no longer works, because the code uses bootstrap's js file and jquery. Perhaps we should remove the dropdown related code from this example and just show the input code?

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects-2_EL-3489-remove-angularjs-styles/#/css/text-inputs#dropdown-addons

4. Bar Chart

The last two items no longer show a dotted border

image

**Comment by TaraTodd123** [comment]
Looks Good! I've also noticed in the dashboard section that the date is missing on the bottom left of the chart.
dash1
image

**Comment by TaraTodd123** [comment]
Also, just noticed regarding Ashley's comment on the Dropdown Addons the fixed width dropdown in the icons section in CSS page isn't working either.
image

**Review by TaraTodd123 — APPROVED** [review]
All looks good! Thanks for the changes.

**Review by ashley-hunter — APPROVED** [review]
All good! Thanks!

**Pull request merged**
