### PR TITLE
EL-3663-Remove-the-bottom-margin

### PR DESCRIPTION
**Pull request by cmallon367**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licenced under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue
https://portal.digitalsafe.net/browse/EL-3663

#### Description of Proposed Changes
Added in bottom-margin to the accordion-panel to ensure the customized examples were the same as the original 
Over-writ the bootstrap style-sheet by adding a label to control.less file
Added styles to the style.less file 

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects-2_EL-3663-Remove-the-bottom-margin

Downstream Build (s)
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/caf_CI_ux-aspects-micro-focus-2_EL-3663-Remove-the-bottom-margin

### CODE REVIEW

**Comment by donna-marijne** [comment]
The PR checklist is malformatted. Please use the [user scripts](https://github.houston.softwaregrp.net/caf/ux-aspects-team/tree/master/userscripts) that we have provided, or refer to other pull requests to see how to fill it in properly.

Example: https://github.houston.softwaregrp.net/caf/quantum/pull/803

**Comment by donna-marijne** [comment]
Missing a pull request for your changes in ux-aspects-micro-focus-2.

**Comment by cmallon367** [comment]
@donna-marijne There's the link to my PR, I left the link on the agile board as well https://github.houston.softwaregrp.net/caf/ux-aspects-micro-focus-2/pull/18

**Review by donna-marijne — APPROVED** [review]
Looks good.

**Pull request merged**
