### PR TITLE
Merge 1.8.17

### PR DESCRIPTION
**Pull request by donna-marijne**
#### Checklist

* [x] The contents of this PR are mine to submit. No third party code or other material is being committed.
* [x] New third party dependencies (if any) are linked via `package.json`. Third party dependencies are licensed under one of the following: Apache, MIT, BSD, Mozilla Public License, Eclipse Public License, or Oracle Binary Code License.
* [x] The code in this PR does not contain export-restricted encryption algorithms.

#### Ticket / Issue

Merge in updates from 1.8.17.

#### Description of Proposed Changes

Merge in updates from 1.8.17.

#### Documentation CI URL

https://pages.github.houston.softwaregrp.net/sepg-docs-qa/UXAspects_CI_UXAspects-2_merge-1.8.17

#### Downstream Build(s)

* [caf/ux-aspects-micro-focus-2](https://jenkins.swinfra.net/job/SEPG/job/caf/job/caf~ux-aspects-micro-focus-2~merge-1.8.17~CI/)

### CODE REVIEW

**Comment by donna-marijne** [comment]
Please check your changes from the previous sprint have been merged correctly. Don't merge until all reviewers have approved, thanks.

**Review by cmallon367 — APPROVED** [review]
The changes look good to me.

**Review by ashley-hunter — APPROVED** [review]

**Comment by andrewstevenson-microfocus** [comment]
Everything working as expected

**Review by andrewstevenson-microfocus — APPROVED** [review]
Everything is working as expected

**Comment by donna-marijne** [comment]
Thanks all.

**Pull request merged**
